"""first revision

Revision ID: 0405c55f13fe
Revises: 
Create Date: 2022-03-01 01:02:34.454310

"""
from alembic import op
import sqlalchemy as sa
from gino import Gino


# revision identifiers, used by Alembic.
revision = '0405c55f13fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('state', Gino().Enum('OPENED', 'CLOSED', 'TERMINATED', name='gamesessionstate'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_sessions',
    sa.Column('vk_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('gain', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('vk_id', 'session_id')
    )
    op.create_table('players',
    sa.Column('vk_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('money', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('vk_id', 'chat_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    op.drop_table('player_sessions')
    op.drop_table('game_sessions')
    op.drop_table('admins')
    # ### end Alembic commands ###
