"""first migration

Revision ID: 994cd0e8f1db
Revises: 
Create Date: 2022-02-26 21:32:29.360694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '994cd0e8f1db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admins')
    # ### end Alembic commands ###
