"""third revision

Revision ID: ff7d32078e40
Revises: 
Create Date: 2022-03-09 16:10:43.390363

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from gino import Gino


gino_orm = Gino()

# revision identifiers, used by Alembic.
revision = 'ff7d32078e40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_chats',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('chat_id'),
    sa.UniqueConstraint('chat_id')
    )
    op.create_table('user_profiles',
    sa.Column('vk_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.Unicode(), nullable=True),
    sa.Column('last_name', sa.Unicode(), nullable=True),
    sa.Column('city', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('vk_id'),
    sa.UniqueConstraint('vk_id')
    )
    op.create_table('game_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('state', gino_orm.Enum('OPENED', 'CLOSED', 'TERMINATED', name='gamesessionstate'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['game_chats.chat_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vk_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('money', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['game_chats.chat_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vk_id'], ['user_profiles.vk_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('players_skey', 'players', ['vk_id', 'chat_id'], unique=True)
    op.create_table('player_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_session_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('bet', sa.Integer(), nullable=True),
    sa.Column('payout_ratio', sa.Integer(), nullable=True),
    sa.Column('state', gino_orm.Enum('BETTING', 'WAITING', 'DEALING', 'STANDING', 'BLACKJACKED', 'BUSTED', 'PAIDOUT', 'CUTOUT', name='playersessionstate'), nullable=False),
    sa.ForeignKeyConstraint(['game_session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('player_sessions.skey', 'player_sessions', ['player_id', 'game_session_id'], unique=True)
    op.create_table('card_deals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_session_id', sa.Integer(), nullable=True),
    sa.Column('card_rank', gino_orm.Enum('Ace', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten', 'Jack', 'Queen', 'King', name='cardrank'), nullable=False),
    sa.Column('card_suit', gino_orm.Enum('Clubs', 'Diamonds', 'Hearts', 'Spades', name='cardsuit'), nullable=False),
    sa.ForeignKeyConstraint(['player_session_id'], ['player_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_dataports',
    sa.Column('player_session_id', sa.Integer(), nullable=False),
    sa.Column('request_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('response_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['player_session_id'], ['player_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_session_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_dataports')
    op.drop_table('card_deals')
    op.drop_index('player_sessions.skey', table_name='player_sessions')
    op.drop_table('player_sessions')
    op.drop_index('players_skey', table_name='players')
    op.drop_table('players')
    op.drop_table('game_sessions')
    op.drop_table('user_profiles')
    op.drop_table('game_chats')
    op.drop_table('admins')
    # ### end Alembic commands ###
